dofile(blk.modpath().."/coal.lua")
dofile(blk.modpath().."/iron.lua")
dofile(blk.modpath().."/gold.lua")
dofile(blk.modpath().."/diamond.lua")
dofile(blk.modpath().."/ores.lua")
dofile(blk.modpath().."/crafts.lua")