blk.food("apple", {food = 1, fruit = 1, apple = 1}, 10)
blk.food("bread", {food = 1, baked = 1, bread = 1}, 15)
blk.food("melon_slice", {food = 1, fruit = 1, melon = 1}, 10)
blk.food("pumpkin_pie", {food = 1, fruit = 1, pie = 1, baked = 1}, 20)
blk.food("raw_beef", {food = 1, meat = 1, raw = 1, beef = 1}, -20)
blk.food("beef", {food = 1, meat = 1, cooked = 1, beef = 1}, 20)
blk.food("raw_mutton", {food = 1, meat = 1, raw = 1, mutton = 1}, -20)
blk.food("mutton", {food = 1, meat = 1, cooked = 1, mutton = 1}, 20)
blk.food("raw_chicken", {food = 1, meat = 1, raw = 1, chicken = 1}, -15)
blk.food("chicken", {food = 1, meat = 1, cooked = 1, chicken = 1}, 15)
blk.item("egg", {food = 1, raw = 1, egg = 1})
blk.food("fried_egg", {food = 1, cooked = 1, egg = 1}, 10)
blk.food("cookie", {food = 1, dessert = 1, cookie = 1}, 5)
blk.item("sugar", {food = 1, sugar = 1})
blk.item("flour", {food = 1, flour = 1})
blk.food("currents", {food = 1, currents = 1, fruit = 1}, 5)
blk.food("mushroom_stew", {food = 1, cooked = 1, stew = 1}, 15)