local modpath = core.get_modpath(core.get_current_modname())
dofile(modpath.."/scripts/items.lua")
dofile(modpath.."/scripts/food.lua")
dofile(modpath.."/scripts/nodes.lua")
dofile(modpath.."/scripts/plants.lua")
dofile(modpath.."/scripts/crafts.lua")
