local modpath = core.get_modpath(core.get_current_modname())
dofile(modpath.."/items.lua")
dofile(modpath.."/food.lua")
dofile(modpath.."/nodes.lua")
dofile(modpath.."/plants.lua")
dofile(modpath.."/crafts.lua")
