local sound = blk.wool_sounds()
local group = {wool = 1, snappy = 1}
blk.simple_node("wool", group, sound)
blk.simple_node("black_wool", group, sound)
blk.simple_node("blue_wool", group, sound)
blk.simple_node("light_blue_wool", group, sound)
blk.simple_node("red_wool", group, sound)
blk.simple_node("green_wool", group, sound)
blk.simple_node("lime_wool", group, sound)
blk.simple_node("orange_wool", group, sound)
blk.simple_node("brown_wool", group, sound)
blk.simple_node("cyan_wool", group, sound)
blk.simple_node("gray_wool", group, sound)
blk.simple_node("light_gray_wool", group, sound)
blk.simple_node("purple_wool", group, sound)
blk.simple_node("magenta_wool", group, sound)
blk.simple_node("pink_wool", group, sound)
