dofile(blk.modpath().."/wood.lua")
dofile(blk.modpath().."/stone.lua")
dofile(blk.modpath().."/iron.lua")
dofile(blk.modpath().."/gold.lua")
dofile(blk.modpath().."/diamond.lua")
dofile(blk.modpath().."/crafts.lua")
