local modpath = core.get_modpath(core.get_current_modname())
dofile(modpath.."/wood.lua")
dofile(modpath.."/stone.lua")
dofile(modpath.."/iron.lua")
dofile(modpath.."/gold.lua")
dofile(modpath.."/diamond.lua")
dofile(modpath.."/crafts.lua")
