local sound = blk.sounds("wool")
local group = {wool = 1, snappy = 1}
local function wool(color)
  if color == nil then return end
  blk.simple_node(color.."_wool", group, sound)
end
wool("white")
blk.alias("white_wool", "wool")
wool("black")
wool("blue")
wool("light_blue")
wool("red")
wool("green")
wool("lime")
wool("orange")
wool("brown")
wool("cyan")
wool("gray")
wool("light_gray")
wool("purple")
wool("magenta")
wool("pink")